version: '2'
networks:
    arvardos-net:

services:
    base:
        build: images/base/
        command: /bin/true
        image: cromulent/base

    passenger:
        build: images/passenger/
        command: /bin/true
        image: cromulent/passenger

    proxy:
        build: images/proxy
        ports:
            - 80:80
            - 443:443
        networks:
            - arvardos-net

    database:
        image: postgres:9.3.13
        networks:
            - arvardos-net
        environment:
            - POSTGRES_PASSWORD=ibahahGho0EYaichieh6ietahsheagiN
            - POSTGRES_USER=root

    # SSO Server
    sso:
        build: images/sso/
        links:
            - database
            - proxy
        networks:
            - arvardos-net
        environment:
            - UUID_PREFIX=${UUID_PREFIX}
            - SECRET_TOKEN=oodaeS3ejash9Woh1ahleeNg8soazahp
            - SSO_DEFAULT_LINK_URL=http://sso.${ARVADOS_DOMAIN}
            - POSTGRES_PASSWORD=Dib7auyaejao8aenu8aiTh4ribaeM6ai
            - PGUSER=root
            - PGPASSWORD=Dib7auyaejao8aenu8aiTh4ribaeM6ai
            - PGHOST=database
            - RAILS_ENV=production

    # API Server
    api:
        build: images/api/
        links:
            - database
            - sso:sso.${ARVADOS_DOMAIN}
            - proxy
        networks:
            - arvardos-net
        environment:
            - RAILS_ENV=production
            - UUID_PREFIX=${UUID_PREFIX}
            - VM_UUID_PREFIX=2s4uqhvwo1f21sp-${UUID_PREFIX}
            - SECRET_TOKEN=oodaeS3ejash9Woh1ahleeNg8soazahp
            - PGUSER=root
            - PGPASSWORD=Dib7auyaejao8aenu8aiTh4ribaeM6ai
            - PGHOST=database
            - BLOB_SIGNING_KEY=AhquohPeeshahyoiKah2ahp1ciethu9x
            - SSO_APP_ID=arvados-server
            - SSO_APP_SECRET=phooshu9eewohBeengiePaequeje9bei
            - SSO_PROVIDER_URL=https://sso.${ARVADOS_DOMAIN}
            - WORKBENCH_ADDRESS=https://workbench.${ARVADOS_DOMAIN}
            - WEBSOCKET_ADDRESS=wss://127.0.0.1:8100/websocket

    # Workbench Server
    workbench:
        build: images/workbench/
        links:
            - api
            - sso
            - proxy
        networks:
            - arvardos-net
        environment:
            - UUID_PREFIX=${UUID_PREFIX}
            - SECRET_TOKEN=oodaeS3ejash9Woh1ahleeNg8soazahp
            - PGUSER=root
            - PGPASSWORD=Dib7auyaejao8aenu8aiTh4ribaeM6ai
            - PGHOST=database
            - ARVADOS_LOGIN_BASE=http://${UUID_PREFIX}.${ARVADOS_DOMAIN}/login
            - ARVADOS_V1_BASE=http://${UUID_PREFIX}.${ARVADOS_DOMAIN}/arvados/v1/
            - ARVADOS_INSECURE_HTTPS=true
            - RAILS_ENV=production
