version: '2'
networks:
    arvardos-net:

services:
    base:
        build: images/base/
        command: /bin/true
        image: cromulent/base
        env_file:
             - "$ARVADOS_DOMAIN.env"
        networks:
            - arvardos-net

    passenger:
        build: images/passenger/
        command: /bin/true
        image: cromulent/passenger

    proxy:
        build: images/proxy
        ports:
            - 80:80
            - 443:443
        networks:
            - arvardos-net
        env_file:
             - "$ARVADOS_DOMAIN.env"

    database:
        image: postgres:9.3.13
        networks:
            - arvardos-net
        env_file:
             - "$ARVADOS_DOMAIN.env"

    # SSO Server
    sso:
        build: images/sso/
        links:
            - database
            - proxy
        networks:
            - arvardos-net
        env_file:
             - "$ARVADOS_DOMAIN.env"

    # API Server
    api:
        build: images/api/
        links:
            - database
            - sso:sso.${ARVADOS_DOMAIN}
            - proxy
        networks:
            - arvardos-net
        env_file:
             - "$ARVADOS_DOMAIN.env"

    # Workbench Server
    workbench:
        build: images/workbench/
        links:
            - api
            - sso
            - proxy
        networks:
            - arvardos-net
        env_file:
             - "$ARVADOS_DOMAIN.env"

