production:
  secret_token: <%= ENV['SECRET_TOKEN'] %>
  arvados_login_base: <%= ENV['ARVADOS_LOGIN_BASE'] %>
  arvados_v1_base: <%= ENV['ARVADOS_V1_BASE'] %>
  arvados_insecure_https: <%= ENV['ARVADOS_INSECURE_HTTPS'] %>
  force_ssl: false
  cache_classes: true
  eager_load: true
  consider_all_requests_local: false
  action_controller.perform_caching: true
  serve_static_assets: false
  assets.compile: false
  assets.digest: true
  i18n.fallbacks: true
  active_support.deprecation: :notify
  profiling_enabled: false
  arvados_insecure_https: false
  data_import_dir: /data/arvados-workbench-upload/data
  data_export_dir: /data/arvados-workbench-download/data
  site_name: Arvados Workbench

