development:
  adapter: postgresql
  template: template0
  encoding: utf8
  database: arvados_development
  username: arvados
  password: arvados
  host: database

test:
  adapter: postgresql
  template: template0
  encoding: utf8
  database: arvados_test
  username: arvados
  password: arvados
  host: database

production:
  adapter: postgresql
  template: template0
  encoding: utf8
  database: arvados_production
  username: arvados
  password: arvados
  host: database
  # For the websockets server, prefer a larger database connection pool size since it
  # multithreaded and can serve a large number of long-lived clients.  See also
  # websocket_max_connections configuration option.
  pool: 50
